[pytest]
filterwarnings =
    ignore:PyPDF2 is deprecated\. Please move to the pypdf library instead\.:DeprecationWarning
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
